apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
data:
  auth-secret: YTkyNDM5YTEtMGEzMy00MmMwLWE1ZTctNzc0MzU4NjE2Y2Ji
  mongodb-uri: bW9uZ29kYitzcnY6Ly90ZWNoY2hhbGxlbmdlOjJteURnM0I5MVRVV0x2cEFAZGV2LWNsdXN0ZXIub2s1aHBydC5tb25nb2RiLm5ldA==
