apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: auth-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/tech-challenge-auth/dev/MONGODB_DATABASE"
        objectType: "ssmparameter"
        objectAlias: mongoDatabase
      - objectName: "/tech-challenge-auth/dev/MONGODB_URI"
        objectType: "ssmparameter"
        objectAlias: mongoURI
      - objectName: "/tech-challenge-auth/dev/AUTH_SECRET"
        objectType: "ssmparameter"
        objectAlias: authSecret
  secretObjects:
    - secretName: auth-secrets-aws
      type: Opaque
      data:
        - objectName: mongoDatabase
          key: mongoDatabase
        - objectName: mongoURI
          key: mongoURI
        - objectName: authSecret
          key: authSecret